import type { Metadata } from "next";
import "./globals.css";
import { Toaster as Sonner } from "@/components/ui/sonner";
import AuthProvider from "@/providers/auth-provider";
import ThemeProvider from "@/providers/theme-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
import { ReactLenis } from "lenis/react";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`font-sans`}>
                <ReactLenis root>
                    <AuthProvider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="light"
                            enableSystem
                            disableTransitionOnChange
                        >
                            {children}
                            <Sonner
                                richColors
                                expand={true}
                                position="top-right"
                            />
                        </ThemeProvider>
                    </AuthProvider>
                </ReactLenis>
            </body>
        </html>
    );
}
