import type { Metadata } from "next";
import "./globals.css";
import { Toaster as Sonner } from "@/components/ui/sonner";
import AuthProvider from "@/providers/auth-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`font-sans`}
            >
                <AuthProvider>
                    {children}
                    <Sonner richColors expand={true} position="top-right" />
                </AuthProvider>
            </body>
        </html>
    );
}
