// @ts-nocheck
// This file is autogenerated by scripts/create-registry.js
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {

      "hero-1": {
        name: "hero-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/hero/hero1.tsx",
                            type: "registry:page",
                            target: "/sections/hero"
                    },{
                            path: "registry/default/sections/footer/footer1.tsx",
                            type: "registry:page",
                            target: "/sections/footer"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/hero/hero1.tsx")),
      },
      "hero-2": {
        name: "hero-2",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/hero/hero2.tsx",
                            type: "registry:page",
                            target: "/sections/hero"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/hero/hero2.tsx")),
      },
      "hero-3": {
        name: "hero-3",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/hero/hero3.tsx",
                            type: "registry:page",
                            target: "/sections/hero"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/hero/hero3.tsx")),
      },
      "hero-4": {
        name: "hero-4",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/hero/hero4.tsx",
                            type: "registry:page",
                            target: "/sections/hero"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/hero/hero4.tsx")),
      },
      "hero-5": {
        name: "hero-5",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/hero/hero5.tsx",
                            type: "registry:page",
                            target: "/sections/hero"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/hero/hero5.tsx")),
      },
      "banner-1": {
        name: "banner-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/banner/banner1.tsx",
                            type: "registry:page",
                            target: "/sections/banner"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/banner/banner1.tsx")),
      },
      "blog-1": {
        name: "blog-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/blog/blog1.tsx",
                            type: "registry:page",
                            target: "/sections/blog"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/blog/blog1.tsx")),
      },
      "blog-2": {
        name: "blog-2",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/blog/blog2.tsx",
                            type: "registry:page",
                            target: "/sections/blog"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/blog/blog2.tsx")),
      },
      "blog-3": {
        name: "blog-3",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/blog/blog3.tsx",
                            type: "registry:page",
                            target: "/sections/blog"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/blog/blog3.tsx")),
      },
      "blog-4": {
        name: "blog-4",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/blog/blog4.tsx",
                            type: "registry:page",
                            target: "/sections/blog"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/blog/blog4.tsx")),
      },
      "blog-5": {
        name: "blog-5",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/blog/blog5.tsx",
                            type: "registry:page",
                            target: "/sections/blog"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/blog/blog5.tsx")),
      },
      "blog-6": {
        name: "blog-6",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/blog/blog6.tsx",
                            type: "registry:page",
                            target: "/sections/blog"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/blog/blog6.tsx")),
      },
      "career-1": {
        name: "career-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/career/career1.tsx",
                            type: "registry:page",
                            target: "/sections/career"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/career/career1.tsx")),
      },
      "contact-1": {
        name: "contact-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/contact/contact1.tsx",
                            type: "registry:page",
                            target: "/sections/contact"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/contact/contact1.tsx")),
      },
      "contact-2": {
        name: "contact-2",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/contact/contact2.tsx",
                            type: "registry:page",
                            target: "/sections/contact"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/contact/contact2.tsx")),
      },
      "cta-1": {
        name: "cta-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/cta/cta1.tsx",
                            type: "registry:page",
                            target: "/sections/cta"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/cta/cta1.tsx")),
      },
      "faq-1": {
        name: "faq-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/faq/faq1.tsx",
                            type: "registry:page",
                            target: "/sections/faq"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/faq/faq1.tsx")),
      },
      "feature-1": {
        name: "feature-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/feature/feature1.tsx",
                            type: "registry:page",
                            target: "/sections/feature"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/feature/feature1.tsx")),
      },
      "footer-1": {
        name: "footer-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/footer/footer1.tsx",
                            type: "registry:page",
                            target: "/sections/footer"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/footer/footer1.tsx")),
      },
      "footer-2": {
        name: "footer-2",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/footer/footer2.tsx",
                            type: "registry:page",
                            target: "/sections/footer"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/footer/footer2.tsx")),
      },
      "footer-3": {
        name: "footer-3",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/footer/footer3.tsx",
                            type: "registry:page",
                            target: "/sections/footer"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/footer/footer3.tsx")),
      },
      "login-1": {
        name: "login-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/login/login1.tsx",
                            type: "registry:page",
                            target: "/sections/login"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/login/login1.tsx")),
      },
      "login-2": {
        name: "login-2",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/login/login2.tsx",
                            type: "registry:page",
                            target: "/sections/login"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/login/login2.tsx")),
      },
      "login-3": {
        name: "login-3",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/login/login3.tsx",
                            type: "registry:page",
                            target: "/sections/login"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/login/login3.tsx")),
      },
      "login-4": {
        name: "login-4",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/login/login4.tsx",
                            type: "registry:page",
                            target: "/sections/login"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/login/login4.tsx")),
      },
      "metrics-1": {
        name: "metrics-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/metrics/metrics1.tsx",
                            type: "registry:page",
                            target: "/sections/metrics"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/metrics/metrics1.tsx")),
      },
      "navbar-1": {
        name: "navbar-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/navbar/navbar1.tsx",
                            type: "registry:page",
                            target: "/sections/navbar"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/navbar/navbar1.tsx")),
      },
      "newsletter-1": {
        name: "newsletter-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/newsletter/newsletter1.tsx",
                            type: "registry:page",
                            target: "/sections/newsletter"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/newsletter/newsletter1.tsx")),
      },
      "pricing-1": {
        name: "pricing-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/pricing/pricing1.tsx",
                            type: "registry:page",
                            target: "/sections/pricing"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing1.tsx")),
      },
      "pricing-2": {
        name: "pricing-2",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/pricing/pricing2.tsx",
                            type: "registry:page",
                            target: "/sections/pricing"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing2.tsx")),
      },
      "pricing-3": {
        name: "pricing-3",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/pricing/pricing3.tsx",
                            type: "registry:page",
                            target: "/sections/pricing"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing3.tsx")),
      },
      "pricing-4": {
        name: "pricing-4",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/pricing/pricing4.tsx",
                            type: "registry:page",
                            target: "/sections/pricing"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing4.tsx")),
      },
      "pricing-5": {
        name: "pricing-5",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/pricing/pricing5.tsx",
                            type: "registry:page",
                            target: "/sections/pricing"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing5.tsx")),
      },
      "pricing-6": {
        name: "pricing-6",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/pricing/pricing6.tsx",
                            type: "registry:page",
                            target: "/sections/pricing"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing6.tsx")),
      },
      "pricing-7": {
        name: "pricing-7",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/pricing/pricing7.tsx",
                            type: "registry:page",
                            target: "/sections/pricing"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing7.tsx")),
      },
      "team-1": {
        name: "team-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/team/team1.tsx",
                            type: "registry:page",
                            target: "/sections/team"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/team/team1.tsx")),
      },
      "testimonial-1": {
        name: "testimonial-1",
        type: "registry:block",
        slug: "",
        thumbnail: "",
        number: "",
        files: [{
                            path: "registry/default/sections/testimonial/testimonial1.tsx",
                            type: "registry:page",
                            target: "/sections/testimonial"
                    }],
        component: React.lazy(() => import("@/registry/default/sections/testimonial/testimonial1.tsx")),
      },
}
