// @ts-nocheck
// This file is autogenerated by scripts/create-registry.js
// Do not edit this file directly.
import * as React from "react"

export const Index = {

  "banner": {
    name: "banner",
    type: "registry:section",
    slug: "/sections/banner",
    thumbnail: "https://res.cloudinary.com/dphulm0s9/image/upload/v1737696976/banner.png",
    number: "4",
    registryDependencies: undefined,
    files: ["registry/default/sections/hero/hero1.tsx"],
    component: React.lazy(() => import("@/registry/default/sections/hero/hero1.tsx")),
  },
  "hero-1": {
    name: "hero-1",
    type: "registry:sections",
    slug: "/sections/hero",
    thumbnail: "/images/components/featured-images/hero1.PNG",
    number: "",
    registryDependencies: undefined,
    files: ["registry/default/sections/hero/hero1.tsx"],
    component: React.lazy(() => import("@/registry/default/sections/hero/hero1.tsx")),
  },
}
