// @ts-nocheck
// This file is autogenerated by scripts/create-registry.js
// Do not edit this file directly.
import * as React from "react"

export const Index = {
  "default": {
      "pricing": {
        name: "pricing",
        type: "registry:section",
        slug: "/sections/pricing",
        thumbnail: "https://res.cloudinary.com/dphulm0s9/image/upload/v1751293059/pricing.png",
        number: "4",
        files: ["registry/default/sections/hero/hero1.tsx"],
        component: React.lazy(() => import("@/registry/default/sections/hero/hero1.tsx")),
      },
      "pricing-1": {
        name: "pricing-1",
        type: "registry:sections",
        auth: false,
        pro: false,
        files: ["registry/default/sections/pricing/pricing1.tsx"],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing1.tsx")),
      },
      "pricing-2": {
        name: "pricing-2",
        type: "registry:sections",
        auth: false,
        pro: false,
        files: ["registry/default/sections/pricing/pricing2.tsx"],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing2.tsx")),
      },
      "pricing-3": {
        name: "pricing-3",
        type: "registry:sections",
        auth: false,
        pro: false,
        files: ["registry/default/sections/pricing/pricing3.tsx"],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing3.tsx")),
      },
      "pricing-4": {
        name: "pricing-4",
        type: "registry:sections",
        auth: false,
        pro: false,
        files: ["registry/default/sections/pricing/pricing4.tsx"],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing4.tsx")),
      },
      "pricing-5": {
        name: "pricing-5",
        type: "registry:sections",
        auth: false,
        pro: false,
        files: ["registry/default/sections/pricing/pricing5.tsx"],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing5.tsx")),
      },
      "pricing-6": {
        name: "pricing-6",
        type: "registry:sections",
        auth: false,
        pro: false,
        files: ["registry/default/sections/pricing/pricing6.tsx"],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing6.tsx")),
      },
      "pricing-7": {
        name: "pricing-7",
        type: "registry:sections",
        auth: false,
        pro: false,
        files: ["registry/default/sections/pricing/pricing7.tsx"],
        component: React.lazy(() => import("@/registry/default/sections/pricing/pricing7.tsx")),
      },
    },
}
